// Expected strings are hand-worked examples, not outputs captured from processors.
export const auditCases={
 'word-counter':[{a:'Hi 👩‍💻',contains:'Words: 1'},{a:'e\u0301',contains:'Characters (graphemes): 1'},{a:'x',o:{wpm:0},error:'Reading speed'},{a:'A short draft.\nIt has two lines.\n\nReview it carefully.',contains:'Paragraphs: 2'},{a:'One line\nwrapped here',contains:'Paragraphs: 1'},{a:' \n\t\n',contains:'Paragraphs: 0'}],
 'text-cleaner':[{a:' A\u00a0 B\r\nC ',text:'A B\nC'},{a:'a\nb\n\nc',o:{join:'paragraphs'},text:'a b\n\nc'},{a:'👩‍💻',text:'👩‍💻'}],
 'remove-duplicate-lines':[{a:' A \na\nB',o:{trim:true,ignoreCase:true},text:' A \nB'},{a:'a\nb\na',o:{keep:'last'},text:'b\na'},{a:'\n\n',text:''}],
 'sort-lines':[{a:'9007199254740993\n9007199254740992',o:{mode:'numeric'},text:'9007199254740992\n9007199254740993'},{a:'-1.0000000000000001\n-1.0000000000000002\n0\n1e-40\n.1',o:{mode:'numeric'},text:'-1.0000000000000002\n-1.0000000000000001\n0\n1e-40\n.1'},{a:'1\nno',o:{mode:'numeric'},error:'decimal number'}],
 'case-converter':[{a:'I İ',o:{mode:'lower',locale:'tr'},text:'ı i'},{a:'hELLO. wORLD!',o:{mode:'sentence'},text:'Hello. World!'}],
 'find-and-replace':[{a:'a,b,c',o:{find:',',replacement:'\n'},text:'a\nb\nc'},{a:'cafe\u0301 cafe',o:{find:'cafe',replacement:'X',whole:true},text:'cafe\u0301 X'},{a:'x',o:{find:''},error:'literal text'}],
 'text-diff':[{a:'same',b:'same',contains:'Unchanged: same'},{a:'',b:'new',contains:'+ Added: new'},{a:'x',b:'',contains:'- Removed: x'}],
 'compare-lists':[{a:'α\nβ\nβ',b:'β\nγ',o:{view:'Union'},text:'α\nβ\nγ'},{a:'',b:'b',o:{view:'Only in B'},text:'b'}],
 'json-formatter':[{a:'{"x":1e400,"__proto__":null}',o:{indent:'0'},text:'{"x":1e400,"__proto__":null}'},{a:'["é",true,null]',o:{indent:'0'},text:'["é",true,null]'},{a:'{"x":1,"\\u0078":2}',error:'Duplicate object key'}],
 'json-to-csv':[{a:'[{"":{"x":1},"x":2}]',o:{safe:false},text:'.x,x\n1,2'},{a:'[{"id":"007"},{"id":null}]',o:{safe:false},text:'id\n007\n'},{a:'[1]',error:'array of objects'}],
 'csv-to-json':[{a:'id\n007',text:'[\n  {"id": "007"}\n]'},{a:'x\n9007199254740993',o:{types:true},text:'[\n  {"x": 9007199254740993}\n]'},{a:'x,x\n1,2',error:'Duplicate column headers'}],
 'csv-viewer':[{a:'a,b\n"x,y","z\nz"',contains:'"x,y","z\nz"'},{a:'a,b\n,',text:'a,b\n,'},{a:'a,b\nx',error:'expected 2'}],
 'csv-deduplicate':[{a:'id,v\n1,old\n2,middle\n1,new',o:{columns:'1',keep:'last'},text:'id,v\n2,middle\n1,new'},{a:'id,v\n1,é\n1,é',text:'id,v\n1,é'},{a:'a\nx',o:{columns:'2'},error:'Column position'}],
 'csv-column-editor':[{a:'id,name\n007,Ada',text:'id,name\n007,Ada'},{a:'x,y\nα,β',text:'x,y\nα,β'},{a:'a,b\n1',error:'expected 2'}],
 'delimiter-converter':[{a:'a,b\n"x,y",z',o:{outDelimiter:';'},text:'a;b\nx,y;z'},{a:'a;b\nx;y',o:{delimiter:';',outDelimiter:'\t'},text:'a\tb\nx\ty'},{a:'a\n"unclosed',error:'Unclosed quoted field'}],
 'csv-merge':[{a:'id\n1',b:'id\n2',text:'id\n1\n2'},{a:'id',b:'id\nα',text:'id\nα'},{a:'a\n1',b:'b\n2',error:'headers do not match'}],
 'csv-split':[{a:'id\n1\n2\n3',o:{rowsPerPart:2},text:'part-001.csv: 2 records\npart-002.csv: 1 records'},{a:'id\nα',o:{rowsPerPart:1},text:'part-001.csv: 1 records'},{a:'id',error:'no data records'}],
 'slug-generator':[{a:'Crème brûlée',text:'creme-brulee'},{a:'你好 世界',o:{mode:'unicode'},text:'你好-世界'},{a:'!!!',error:'No supported characters'}],
 'url-parser':[{a:'https://example.com/?a=1&a=2',contains:'"parameters": ['},{a:'?q=a%2Bb+c',o:{mode:'query'},contains:'a+b c'},{a:'javascript:alert(1)',error:'HTTP and HTTPS'}],
 'url-encoder-decoder':[{a:'é +',text:'%C3%A9%20%2B'},{a:'%2520',o:{action:'decode'},text:'%20'},{a:'%C3%28',o:{action:'decode'},error:'Invalid percent escape'}],
 'utm-builder':[{a:'https://example.com/?q=x#f',o:{source:'A B',medium:'email',campaign:'one'},text:'https://example.com/?q=x&utm_source=A+B&utm_medium=email&utm_campaign=one#f'},{a:'https://example.com/?utm_source=old',o:{source:'new',medium:'m',campaign:'c'},text:'https://example.com/?utm_source=new&utm_medium=m&utm_campaign=c'},{a:'https://example.com',o:{source:''},error:'campaign source'}],
 'url-cleaner':[{a:'https://example.com/?q=a%20b&utm_source=x&q=c+d',text:'https://example.com/?q=a%20b&q=c+d'},{a:'https://example.com/?utm_source=x',o:{utm_source:false},text:'https://example.com/?utm_source=x'},{a:'https://u:p@example.com',error:'embedded credentials'}],
 'color-converter':[{a:'#0f08',contains:'HEX: #00ff0088'},{a:'hsl(-120 100% 50%)',contains:'HEX: #0000ff'},{a:'rgb(1,,2,3)',error:'separators'},{a:'rgb(1 / 2 3)',error:'after all three'}],
 'contrast-checker':[{a:'#000',b:'#fff',contains:'Contrast ratio: 21.00:1'},{a:'#123',b:'#123',contains:'Contrast ratio: 1.00:1'},{a:'#0008',b:'#fff',error:'opaque colors'}],
 'base64':[{a:'你好',text:'5L2g5aW9'},{a:'77u/QQ==',o:{action:'decode'},text:'\ufeffA'},{a:'/w==',o:{action:'decode'},text:'ff'},{a:'Zh==',o:{action:'decode'},error:'padding bits'}],
 'html-entities':[{a:'&lt;script&gt;x&lt;/script&gt;',o:{action:'decode'},text:'<script>x</script>'},{a:'é &',o:{numeric:true},text:'&#233; &#38;'},{a:'&unknown;',o:{action:'decode'},text:'&unknown;'}]
};
