import tools from 'utilitypilot:search-index' with {type:'json'};
const normalize=s=>s.toLowerCase().normalize('NFD').replace(/\p{M}/gu,'').trim();
const aliases={'image size':'image-inspector','word count':'word-counter','delimeter':'delimiter-converter','json beautifier':'json-formatter'};
function matches(q){q=normalize(q);if(!q)return tools;const words=q.split(/\s+/);return tools.map(t=>{const name=normalize(t.name),hay=normalize([t.name,t.slug,t.description,...t.aliases].join(' '));let score=aliases[q]===t.slug?100:name===q?90:t.aliases.some(a=>normalize(a)===q)?85:name.startsWith(q)?70:words.every(w=>name.includes(w))?60:words.every(w=>hay.includes(w))?30:0;return {t,score};}).filter(x=>x.score).sort((a,b)=>b.score-a.score||a.t.name.localeCompare(b.t.name)).map(x=>x.t);}
const categoryNames={text:'Text & Lists',data:'Data & Tables',image:'Images',web:'Web & Publishing',developer:'Developer Tools'},icons={text:'Aa',data:'▦',image:'▧',web:'↗',developer:'{}'};
function element(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
function card(t){const a=element('a',undefined,'tool-card');a.href=t.path;a.dataset.category=t.category;a.dataset.slug=t.slug;const icon=element('span',icons[t.category],'tool-icon '+t.category);icon.setAttribute('aria-hidden','true');const copy=element('span',undefined,'card-copy');copy.append(element('span',t.name,'card-name'),element('span',t.description,'card-description'),element('span',categoryNames[t.category],'card-category'));const arrow=element('span','↗','card-arrow');arrow.setAttribute('aria-hidden','true');a.append(icon,copy,arrow);return a;}
for(const finder of document.querySelectorAll('[data-finder]')){
 const input=finder.querySelector('input'),box=finder.querySelector('[role=listbox]'),status=finder.querySelector('[data-search-status]'),empty=finder.querySelector('[data-search-empty]');let active=-1,found=[];
 const directory=finder.closest('[data-directory]');let category=directory?.dataset.initialCategory||'';
 const close=(clearEmpty=true)=>{box.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;found=[];if(clearEmpty)empty.hidden=true;status.textContent='';};
 function updateDirectory(){if(!directory)return;let list=matches(input.value).filter(t=>!category||t.category===category);if(directory.querySelector('#directory-sort').value==='name')list.sort((a,b)=>a.name.localeCompare(b.name));directory.querySelector('[data-tool-grid]').replaceChildren(...list.map(card));directory.querySelector('[data-directory-count]').textContent=`${list.length} ${list.length===1?'tool':'tools'}`;directory.querySelector('.empty-search').hidden=list.length!==0;}
 const update=()=>{found=matches(input.value).filter(t=>!category||t.category===category).slice(0,6);active=-1;empty.hidden=true;box.replaceChildren();if(!input.value.trim()){close();updateDirectory();return;}found.forEach((t,i)=>{const a=element('a',undefined,'suggestion');a.href=t.path;a.id=input.id+'-option-'+i;a.setAttribute('role','option');a.setAttribute('aria-selected','false');a.append(element('strong',t.name),element('small',categoryNames[t.category]+' · '+t.description));box.append(a);});if(!found.length){close();empty.textContent='No matching tools. Try text, CSV, image or URL.';empty.hidden=false;status.textContent=empty.textContent;updateDirectory();return;}box.hidden=false;input.setAttribute('aria-expanded','true');status.textContent=`${found.length} suggestions`;updateDirectory();};
 // Keep the empty-state message in place on blur so nearby controls do not
 // move between pointer-down and click. Query changes clear it explicitly.
 finder.addEventListener('focusout',e=>{if(!finder.contains(e.relatedTarget))close(false);});input.addEventListener('input',update);input.addEventListener('focus',()=>{if(input.value)update();});
 input.addEventListener('keydown',event=>{if(event.key==='Escape'){close();return;}if(['ArrowDown','ArrowUp'].includes(event.key)){event.preventDefault();if(box.hidden)update();if(!found.length)return;active=active===-1?(event.key==='ArrowDown'?0:found.length-1):(active+(event.key==='ArrowDown'?1:-1)+found.length)%found.length;[...box.children].forEach((a,i)=>a.setAttribute('aria-selected',String(i===active)));input.setAttribute('aria-activedescendant',box.children[active].id);}if(event.key==='Enter'){event.preventDefault();if(!box.hidden&&found.length)location.href=found[Math.max(0,active)].path;}});
 finder.querySelector('[data-clear-search]').addEventListener('click',()=>{input.value='';close();updateDirectory();input.focus();});
 document.addEventListener('click',e=>{if(!finder.contains(e.target))close(false);});
 if(directory){directory.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{category=button.dataset.filter;directory.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));close();updateDirectory();}));directory.querySelector('#directory-sort').addEventListener('change',updateDirectory);directory.querySelector('[data-clear-filters]').addEventListener('click',()=>{input.value='';category='';directory.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter==='')));close();updateDirectory();input.focus();});}
}
const report=document.querySelector('#report-form');
if(report){let output='';const status=report.querySelector('[role=status]'),preview=report.querySelector('#report-output');report.addEventListener('submit',e=>{e.preventDefault();if(!report.reportDetails.value.trim()){status.textContent='Describe the issue before preparing a report.';report.reportDetails.focus();return;}output=`UtilityPilot issue report\nTool: ${report.reportTool.value}\nIssue: ${report.reportDetails.value}\nExpected: ${report.expected.value}\nBrowser (optional): ${report.browser.value}\nReply email (optional): ${report.reply.value}\n\nNo tool input has been attached automatically.\n`;preview.value=output;report.querySelector('#prepared-report').hidden=false;status.textContent='Report prepared locally. Review it before sharing.';});report.querySelector('#copy-report').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output);status.textContent='Report copied.';}catch{preview.focus();preview.select();status.textContent='Clipboard permission was unavailable. The report is selected for manual copying.';}});report.querySelector('#download-report').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([output],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='utilitypilot-report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);status.textContent='Report downloaded. No report was sent.';});report.querySelector('#email-report')?.addEventListener('click',()=>{location.href='mailto:'+report.dataset.email+'?subject='+encodeURIComponent('UtilityPilot tool issue')+'&body='+encodeURIComponent(output);});report.addEventListener('input',()=>{output='';preview.value='';report.querySelector('#prepared-report').hidden=true;});window.addEventListener('pagehide',()=>report.reset());report.addEventListener('reset',()=>{preview.value='';output='';report.querySelector('#prepared-report').hidden=true;status.textContent='Report cleared.';});}
