import {configs} from '../data/configs.mjs';
const root=document.querySelector('[data-tool]');
const slug=root.dataset.tool,category=root.dataset.toolCategory,config=configs[slug],form=document.querySelector('#tool-form');
const $=s=>document.querySelector(s),inputA=$('#input-a'),inputB=$('#input-b'),error=$('#tool-error'),status=$('#tool-status'),output=$('#output'),resultPanel=$('#result');
const treeRenderer=slug==='json-viewer'?(await import('./json-tree.mjs')).renderTree:null;
let worker,timeout,controller,version=0,current=null,source=null,imageModule=null,files=[],columns=null,objectURLs=[];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
function release(){objectURLs.forEach(URL.revokeObjectURL);objectURLs=[];}
function stop(){version++;worker?.terminate();worker=null;clearTimeout(timeout);controller?.abort();controller=null;$('#run').disabled=false;$('#cancel').hidden=true;}
function clearResult(){stop();release();current=null;resultPanel.hidden=true;output.value='';$('#rich-result').replaceChildren();$('#part-downloads').replaceChildren();error.hidden=true;status.textContent='';}
function fail(message){error.textContent=message;error.hidden=false;status.textContent='No result created. Check the input or options.';error.focus();}
function options(){return Object.fromEntries(config.options.map(f=>{const n=form.elements.namedItem(f.key);return [f.key,f.type==='checkbox'?n.checked:n.value];}));}
function download(data,name,type='text/plain;charset=utf-8'){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob);objectURLs.push(url);const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>{URL.revokeObjectURL(url);objectURLs=objectURLs.filter(x=>x!==url);},5000);}
function render(result){
 current=result;output.value=result.text;$('#result-summary').textContent=result.summary;const rich=$('#rich-result');rich.replaceChildren();
 if(result.tree&&treeRenderer)treeRenderer(rich,result.tree);
 if(result.stats){const dl=el('dl',undefined,'stats-grid');for(const [k,v] of Object.entries(result.stats)){const div=el('div',undefined,'stat');div.append(el('dt',k),el('dd',String(v)));dl.append(div);}rich.append(dl);}
 if(result.table){const wrap=el('div',undefined,'table-scroll');wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Result table');const table=el('table'),caption=el('caption',`Preview: ${Math.min(50,result.table.rows.length)} of ${result.table.total} records. Full output is available below.`),head=el('thead'),tr=el('tr');result.table.headers.forEach(h=>{const th=el('th',h);th.scope='col';tr.append(th);});head.append(tr);const body=el('tbody');result.table.rows.slice(0,50).forEach(row=>{const tr=el('tr');row.forEach(v=>tr.append(el('td',String(v))));body.append(tr);});table.append(caption,head,body);wrap.append(table);rich.append(wrap);}
 if(result.diff){const div=el('div',undefined,'diff-output');for(const p of result.diff){const row=el('div',undefined,p.added?'added':p.removed?'removed':'unchanged');row.append(el('strong',p.added?'Added: ':p.removed?'Removed: ':'Unchanged: '),document.createTextNode(p.value));div.append(row);}rich.append(div);}
 if(result.swatch){const swatch=el('div',undefined,'swatch');swatch.style.backgroundColor=result.swatch;swatch.setAttribute('role','img');swatch.setAttribute('aria-label','Color swatch '+result.swatch);rich.append(swatch);}
 if(result.contrast){const preview=el('div','The quick brown fox jumps over the lazy dog.', 'contrast-preview');preview.style.color=result.contrast.foreground;preview.style.backgroundColor=result.contrast.background;preview.style.fontSize=result.contrast.size+'px';preview.style.fontWeight=result.contrast.bold?'700':'400';rich.append(preview);}
 if(result.image&&result.blob){const img=el('img',undefined,'output-image'),url=URL.createObjectURL(result.blob);objectURLs.push(url);img.src=url;img.width=Number(result.stats['Width (px)']);img.height=Number(result.stats['Height (px)']);img.decoding='async';img.alt=`Processed image preview: ${img.width} by ${img.height} pixels`;rich.append(img);}
 $('#part-downloads').replaceChildren();if(result.parts)result.parts.forEach(p=>{const b=el('button',`Download ${p.name} (${p.rows} records)`,'button secondary small');b.type='button';b.addEventListener('click',()=>download(p.text,p.name,'text/csv;charset=utf-8'));$('#part-downloads').append(b);});
 resultPanel.hidden=false;error.hidden=true;status.textContent='Result ready. Review the output below.';
}
async function process(event){event?.preventDefault();clearResult();const job=version;$('#run').disabled=true;$('#cancel').hidden=false;status.textContent='Processing locally…';const o=options();if(config.columns&&columns)o.columnConfig=columns;
 try{
  if(config.image){controller=new AbortController();imageModule??=await import('./image-client.mjs');const r=await imageModule.runImage(slug,source,o,controller.signal);if(job===version)render(r);}
  else {worker=new Worker('/assets/worker.js',{type:'module'});await new Promise((resolve,reject)=>{worker.onmessage=({data})=>{if(data.error)reject(Error(data.error));else {if(job===version)render(data.result);resolve();}};worker.onerror=()=>reject(Error('The local processor could not start. Reload this page and try again.'));timeout=setTimeout(()=>{worker?.terminate();reject(Error('Processing exceeded 8 seconds. Try a smaller input.'));},8000);worker.postMessage({category,slug,a:inputA?.value||'',b:inputB?.value||'',options:o,files:files.map(f=>f.text)});});}
 }catch(e){if(job===version)fail(e.message);}finally{if(job===version){worker?.terminate();worker=null;clearTimeout(timeout);$('#run').disabled=false;$('#cancel').hidden=true;}}
}
form.addEventListener('submit',process);$('#cancel').addEventListener('click',()=>{stop();status.textContent='Processing cancelled. Original input retained.';});
form.addEventListener('input',event=>{clearResult();if(event.target===inputA||event.target===inputB){files=[];columns=null;$('#file-list')?.replaceChildren();$('#columns')?.replaceChildren();}if(['opt-header','opt-delimiter'].includes(event.target.id)){columns=null;$('#columns')?.replaceChildren();}if(config.image&&source)imageModule?.syncControls(event.target,source,slug);});
form.addEventListener('reset',()=>{clearResult();source=null;imageModule?.clearSource();files=[];columns=null;$('#file-list')?.replaceChildren();$('#columns')?.replaceChildren();if(config.image){const canvas=$('#source-canvas');canvas.width=1;canvas.height=1;$('.canvas-wrap').hidden=true;$('#image-details').textContent='';}status.textContent='Inputs and results cleared.';});
$('#copy').addEventListener('click',async()=>{if(!current)return;try{await navigator.clipboard.writeText(current.text);status.textContent='Result copied.';}catch{output.focus();output.select();status.textContent='Clipboard unavailable. Output selected for manual copying.';}});
$('#download').addEventListener('click',()=>{if(!current)return;download(current.blob||current.bytes||current.text,current.filename,current.mime);status.textContent='Download requested. The result remains available.';});
async function setImage(file){clearResult();const job=version;source=null;imageModule?.clearSource();$('#image-details').textContent='';$('.canvas-wrap').hidden=true;try{imageModule??=await import('./image-client.mjs');const loaded=await imageModule.loadImage(file);if(job!==version)return;source=loaded;imageModule.displaySource(source,slug,clearResult);status.textContent='Image ready. Adjust options, then process.';}catch(e){if(job===version)fail(e.message);}}
if(config.image){$('#image-file').addEventListener('change',event=>setImage(event.target.files[0]));const drop=$('.file-drop');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag-over');});drop.addEventListener('dragleave',()=>drop.classList.remove('drag-over'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag-over');if(e.dataTransfer.files.length!==1){fail('Choose one image at a time.');return;}setImage(e.dataTransfer.files[0]);});}
$('#sample').addEventListener('click',async()=>{clearResult();const sampleVersion=version;if($('#text-file'))$('#text-file').value='';if($('#image-file'))$('#image-file').value='';files=[];columns=null;$('#file-list')?.replaceChildren();$('#columns')?.replaceChildren();if(config.image){const canvas=document.createElement('canvas');canvas.width=400;canvas.height=300;const ctx=canvas.getContext('2d');ctx.fillStyle='#dce8c8';ctx.fillRect(0,0,400,300);ctx.fillStyle='#205a43';ctx.fillRect(0,0,200,150);ctx.fillStyle='#c5a06e';ctx.fillRect(200,150,200,150);ctx.clearRect(340,0,60,60);await new Promise(resolve=>canvas.toBlob(async b=>{if(sampleVersion!==version){resolve();return;}await setImage(new File([b],'sample.png',{type:'image/png'}));resolve();}));}else{if(inputA)inputA.value=config.sample||'';if(inputB)inputB.value=config.sampleB||'';status.textContent='Sample input loaded. Run the tool to see a real result.';}});
async function readFile(file){if(file.size>5242880)throw Error('Each text/data file must be no larger than 5 MiB.');if(file.size===0)throw Error('The selected file is empty.');try{return new TextDecoder($('#file-encoding').value,{fatal:true}).decode(await file.arrayBuffer());}catch{throw Error('File could not be decoded with the selected encoding. Choose the source encoding and select the file again.');}}
function fileList(){const list=$('#file-list');list.replaceChildren();files.forEach((f,i)=>{const row=el('div',undefined,'file-row');row.append(el('span',`${i+1}. ${f.name}`));for(const [label,delta] of [['Move up',-1],['Move down',1]]){const button=el('button',delta===-1?'↑':'↓');button.type='button';button.setAttribute('aria-label',`${label}: ${f.name}`);button.disabled=i+delta<0||i+delta>=files.length;button.addEventListener('click',()=>{clearResult();[files[i],files[i+delta]]=[files[i+delta],files[i]];fileList();});row.append(button);}list.append(row);});}
$('#text-file')?.addEventListener('change',async event=>{clearResult();const job=version;files=[];columns=null;$('#columns')?.replaceChildren();$('#file-list')?.replaceChildren();const chosen=[...event.target.files];try{if(config.multiple&&(chosen.length>10||chosen.reduce((n,f)=>n+f.size,0)>10485760))throw Error('Choose up to 10 files, no more than 10 MiB combined.');const loaded=await Promise.all(chosen.map(async f=>({name:f.name,text:await readFile(f)})));if(job!==version)return;if(config.multiple){files=loaded;inputA.value='';inputB.value='';fileList();}else inputA.value=loaded[0]?.text||'';status.textContent='File input loaded locally.';}catch(e){if(job===version)fail(e.message);}});
$('#file-encoding')?.addEventListener('change',()=>{clearResult();files=[];inputA.value='';if(inputB)inputB.value='';$('#text-file').value='';$('#file-list').replaceChildren();status.textContent='Encoding changed. Select the file again to decode it.';});
function renderColumns(){const container=$('#columns');container.replaceChildren();columns.forEach((c,i)=>{const row=el('div',undefined,'column-row');const label=el('label'),checkbox=el('input');checkbox.type='checkbox';checkbox.checked=c.keep;checkbox.addEventListener('change',()=>{c.keep=checkbox.checked;clearResult();});label.append(checkbox,document.createTextNode(`Column ${c.index+1}`));const name=el('input');name.type='text';name.value=c.name;name.setAttribute('aria-label',`Header for original column ${c.index+1}`);name.addEventListener('input',()=>c.name=name.value);row.append(label,name);for(const [label,delta] of [['Move column up',-1],['Move column down',1]]){const b=el('button',delta<0?'↑':'↓');b.type='button';b.setAttribute('aria-label',`${label}: ${c.name}`);b.disabled=i+delta<0||i+delta>=columns.length;b.addEventListener('click',()=>{clearResult();[columns[i],columns[i+delta]]=[columns[i+delta],columns[i]];renderColumns();});row.append(b);}container.append(row);});}
$('#load-columns')?.addEventListener('click',async()=>{clearResult();const job=version;try{const {table}=await import('../lib/data.mjs');if(job!==version)return;const t=table(inputA.value,options());columns=t.headers.map((name,index)=>({name,index,keep:true}));renderColumns();status.textContent='Column controls loaded. Changes apply when you run the tool.';}catch(e){fail(e.message);}});
window.addEventListener('pagehide',()=>{stop();release();source=null;files=[];columns=null;current=null;form.reset();output.value='';});
